.github/workflows/backend-ci.yml

Github Action CI 구축
- #15 
백엔드 ci 구축했습니다. 확인 부탁드려요!
(개인 레포에서 ci 테스트 해보고 진행했습니다.)

[Backend] init: GitHub Action CI 구축

---

.github/labeler.yml
.github/workflows/label.yml

user 이름에 따라 자동 라벨링 되도록 기능 추가했습니다.
- #14
user 이름에 따라 라벨링되도록 구현했지만 title 양식은
'[스택] feat: 어쩌구저쩌구'의 형식 맞춰주세요!
+) 추가로 이슈랑 pr 만들 때 본인 assign 하는 거 까먹지 말기 ~~

[Frontend/Backend/AI] user 이름 기반 라벨링 자동화

---

frontend/src/components/Monitoring/AlertList/EmptyView.tsx

icon 폴더 새로 만들면서 import 경로 수정해줘야 되는데 깜빡했습니다..
- #12

[Frontend] chore: import 파일 경로 수정

---

backend/build.gradle
backend/src/main/java/com/example/backend/dashboard/controller/DashboardController.java
backend/src/main/java/com/example/backend/dashboard/domain/CaseEntity.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseRequest.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseResponse.java
backend/src/main/java/com/example/backend/dashboard/dto/SurveyRequest.java
backend/src/main/java/com/example/backend/dashboard/dto/SurveyResponse.java
backend/src/main/java/com/example/backend/dashboard/repository/CaseRepository.java
backend/src/main/java/com/example/backend/dashboard/service/DashboardService.java

메인 페이지의 출동 사건과 관련된 API 개발 및 설문조사 API 개발
- #30 
- 메인 페이지의 출동 사건 조회/완료 API 추가
- AI 분류 부정확도에 대한 설문조사 API 추가
피드백 부탁드립니다.

[Backend] feat: 메인 페이지 - 출동 사건 관련 API

---

backend/src/main/java/com/example/backend/dashboard/controller/DashboardController.java
backend/src/main/java/com/example/backend/dashboard/domain/CaseEntity.java
backend/src/main/java/com/example/backend/dashboard/domain/CctvEntity.java
backend/src/main/java/com/example/backend/dashboard/domain/PoliceEntity.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseResponse.java
backend/src/main/java/com/example/backend/dashboard/repository/CaseRepository.java
backend/src/main/java/com/example/backend/dashboard/service/DashboardService.java

메인 페이지 User Session 적용 및 리팩토링
- #43 
메인 페이지에 User Session 적용해서 각 API 에 office_id 로 필터링 걸었습니다.
또 기존 출동 중인 사건 response를 프론트에서 원하는 값들로 변경 후 전체적인 코드 리팩토링 진행하였습니다.
리뷰 부탁드려요~

[Backend] feat: 메인 페이지 User Session 적용

---

frontend/package.json
frontend/src/components/Monitoring/AlertList/AlertItem.tsx
frontend/src/components/Monitoring/AlertModal/AlertModal.style.ts
frontend/src/components/Monitoring/AlertModal/AlertModal.tsx
frontend/src/components/Monitoring/InProgress/IncidentCard.tsx
frontend/src/components/Monitoring/InProgress/VideoModal/VideoModal.tsx
frontend/src/components/Monitoring/InfoSection/InfoSection.tsx
frontend/src/components/common/VideoComponent/VideoComponent.tsx
frontend/src/components/common/VideoComponent/style.ts
frontend/src/hooks/useIsModalOpen.ts
frontend/yarn.lock

react-player video 태그로 변경
- #50
이 전 브랜치에서 했어야했는데 깜빡하고 머지해버려서 여기서 해요 서영언니도 곧 video component 사용해야해서 pr 올렸습니다!
그리고 props로 w, h 넘겨줄 때 px값 말고도 저는 %로 사용하고 싶어서 w, h의 type을 바꿨어요! 사용법은 여전히 똑같습니다

[Frontend] refactor: react-player video 태그로 변경

---

backend/src/main/java/com/example/backend/analysis/controller/CaseStatsController.java
backend/src/main/java/com/example/backend/analysis/domain/CaseStatsCategoryEntity.java
backend/src/main/java/com/example/backend/analysis/domain/CaseStatsOverviewEntity.java
backend/src/main/java/com/example/backend/analysis/domain/CctvEntity.java
backend/src/main/java/com/example/backend/analysis/domain/OfficeEntity.java
backend/src/main/java/com/example/backend/analysis/dto/CaseStatsOverviewResponse.java
backend/src/main/java/com/example/backend/analysis/dto/CctvCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/DailyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/HourlyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/MonthlyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/repository/CaseStatsCategoryRepository.java
backend/src/main/java/com/example/backend/analysis/repository/CaseStatsOverviewRepository.java
backend/src/main/java/com/example/backend/analysis/service/CaseStatsService.java

통계 페이지에 대한 API 개발
- #39 
통계 페이지에 필요한 API 개발 완료했습니다.
Overview는 추후 논의 후 관련 테이블 제거 후 Case 테이블에서 조회하려고 합니다.
구현 내용
- 시간대별, 일/월별, 유형별, 장소별 사건 통계 조회 API (`/hour`), (`/date`), (`/category`), (`/location`)
- 지도용 장소별 사건 통계 조회 API 따로 개발 (`/map`) 
- 각 API에 대해 유효성 검사 및 예외 처리 추가
- `HttpSession`을 통해 office_id 필터링 적용
프론트에서 사용하는 그래프 구성에 맞춰 응답 형태를 설계하였고,
`category` 및 `period` 파라미터는 대소문자 구분 없이 처리 하였습니다.
리뷰 부탁드립니다 🙇‍♀️

[Backend] feat: 통계 페이지 관련 API 개발

---

backend/src/main/java/com/example/backend/search/controller/SearchController.java
backend/src/main/java/com/example/backend/search/domain/CaseEntity.java
backend/src/main/java/com/example/backend/search/domain/CctvEntity.java
backend/src/main/java/com/example/backend/search/domain/OfficeEntity.java
backend/src/main/java/com/example/backend/search/domain/PoliceEntity.java
backend/src/main/java/com/example/backend/search/domain/SearchSpecification.java
backend/src/main/java/com/example/backend/search/dto/DetailRequest.java
backend/src/main/java/com/example/backend/search/dto/DetailResponse.java
backend/src/main/java/com/example/backend/search/dto/SearchRequest.java
backend/src/main/java/com/example/backend/search/dto/SearchResponse.java
backend/src/main/java/com/example/backend/search/dto/SearchResult.java
backend/src/main/java/com/example/backend/search/repository/CctvRepository.java
backend/src/main/java/com/example/backend/search/repository/SearchRepository.java
backend/src/main/java/com/example/backend/search/service/SearchService.java
backend/src/main/java/com/example/backend/user/controller/UserController.java
backend/src/main/java/com/example/backend/user/domain/UserEntity.java
backend/src/main/java/com/example/backend/user/repository/UserRepository.java

기록 페이지 (search) API
1. 사건 분류 API
- category, startdate, enddate, location || police 조건에 따라 사건 기록 제공
- 페이지네이션(page) 및 정렬(order)
2. 사건 상세 정보 API
- 해당 사건에 대한 상세 정보 (영상, 위도경도)
3. 사건 메모 수정 API
- 해당 사건의 메모 수정
- #36 
저도 마찬가지로 entity로 인해 CI 오류(DuplicateMappingException) 발생한 것 같습니다. 내일 만나서 같이 리팩토링하면 될 것 같습니다!

[Backend] feat: 기록 페이지 관련 API

---

frontend/src/components/IncidentHistory/Filtering/DateFiltering.tsx
frontend/src/components/IncidentHistory/Filtering/SearchBar.tsx
frontend/src/components/IncidentHistory/IncidentList/IncidentList.tsx
frontend/src/components/IncidentHistory/IncidentList/SortingDropDown.tsx
frontend/src/components/Monitoring/AlertList/AlertItem.tsx
frontend/src/components/Monitoring/AlertList/AlertList.tsx
frontend/src/components/Monitoring/AlertModal/AlertModal.tsx
frontend/src/components/Monitoring/AlertModal/CategorySelectModal.tsx
frontend/src/components/Monitoring/AlertModal/IncidentModal.tsx
frontend/src/components/Monitoring/AlertModal/SubmitModal.tsx
frontend/src/components/Monitoring/InProgress/CategorySelectCard.tsx
frontend/src/components/Monitoring/InProgress/FeedbackCard.tsx
frontend/src/components/Monitoring/InProgress/InProgress.tsx
frontend/src/components/Monitoring/InProgress/IncidentCard.tsx
frontend/src/components/Monitoring/InProgress/ResolvedCard.tsx
frontend/src/components/Monitoring/InProgress/VideoModal/VideoModal.tsx
frontend/src/components/Monitoring/InfoSection/InfoSection.tsx
frontend/src/components/common/CategoryDropDown/CategoryDropDown.tsx
frontend/src/components/common/Sidebar/Layout.tsx
frontend/src/components/common/Sidebar/Sidebar.tsx
frontend/src/components/common/Sidebar/SidebarButton.tsx
frontend/src/hooks/useIsModalOpen.ts
frontend/src/mocks/InProgressData.ts
frontend/src/pages/IncidentHistoryPage/IncidentHistoryPage.tsx
frontend/src/pages/MonitoringPage/MonitoringPage.tsx
frontend/src/routes/Router.tsx
frontend/src/stores/itemStore.ts
frontend/tsconfig.app.json

alias 오류 해결
- #24
어떻게 해결했냐면 tsconfig.app.json 파일에 "extends": "./tsconfig.json", 딱 한줄 추가했습니다...ㅎ
그리고 frontend 브랜치에 올라와있는 파일들은 다 수정했어요! 빼먹은 거 있을 수도 있으니까 혹시나 발견하면 수정해주시는 걸로 하고, 
components, constants, hooks, types, mocks, stores .....등등은 src안에 들은 최상위 폴더들인거잖아요? 그래서 @ 가 먹히는데
저희 폴더 구조에서 오로지 딱 common만이 안 먹혀요 얘는 src/ 안에 들은 폴더가 아니라 src/components/ 이라서. 그래서 다른 애들은 다 @로 해도 되고 common만 ```import 뭐시기 from '@/components/common/~~';```로 해주세용
(+ common 말고도 부모 폴더가 src가 아닌 경로가 있다면 얘도 안 먹힐 거니까 @/components/뭐시기컴포넌트, 하시든가 아니면 경로가 그렇게 안 길다면 ../뭐시기컴포넌트 요정도는 해도 괜찮을 거 같아요 ㅎㅎ)
확인하셨으면 알려주세요 ㅎㅎ
@seo0o519 @hummingbbird

[Frontend] fix: alias 오류 해결

---

backend/src/main/java/com/example/backend/analysis/dto/HourlyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/repository/CaseStatsCategoryRepository.java
backend/src/main/java/com/example/backend/common/domain/CaseEntity.java
backend/src/main/java/com/example/backend/common/domain/CaseStatsCategoryEntity.java
backend/src/main/java/com/example/backend/common/domain/CaseStatsOverviewEntity.java

Entity에 assult 를 assault로 수정
- #68 
오타 수정했습니다.. 확인부탁드려요..!

[Backend] fix: Entity Column 오타 수정

---

backend/Dockerfile

AWS instance에서 postgreSQL과 백엔드 서버 배포를 위한 docker 설정입니다.
- #70 
docker-compose.yml은 노션에 올려뒀습니다!

[Backend] feat: 배포 관련 docker 설정

---

backend/src/main/java/com/example/backend/common/GlobalExceptionHandler.java
backend/src/main/java/com/example/backend/dashboard/controller/AlarmListController.java
backend/src/main/java/com/example/backend/dashboard/controller/DashboardController.java
backend/src/main/java/com/example/backend/dashboard/controller/ProgressController.java
backend/src/main/java/com/example/backend/dashboard/dto/ProgressResponse.java
backend/src/main/java/com/example/backend/dashboard/repository/AlarmListRepository.java
backend/src/main/java/com/example/backend/dashboard/repository/ProgressRepository.java
backend/src/main/java/com/example/backend/dashboard/service/AlarmListService.java
backend/src/main/java/com/example/backend/dashboard/service/ProgressService.java
backend/src/main/java/com/example/backend/user/dto/UserResponseDto.java
backend/src/main/java/com/example/backend/user/service/UserService.java

출동 시 담당 경찰관 배정 및 파일 이름 변경
- #72 
출동 시에 담당 경찰관 배정 완료했고, 기존 Case 관련 파일이름도 Progress로 변경 완료했습니다. 
리뷰 부탁드려요~

[Backend] fix: 출동 시 담당 경찰관 배정

---

.github/workflows/backend-ci.yml
backend/build.gradle
backend/src/main/java/com/example/backend/config/CorsConfig.java
backend/src/main/java/com/example/backend/config/SecurityConfig.java

프론트 IP CORS 설정 추가
- #76 
CORS 설정 추가했습니다! 확인 부탁드려요!

[Backend] feat: 프론트 CORS 설정 추가

---

backend/src/main/java/com/example/backend/dashboard/controller/CaseDetectController.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseDetectRequest.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseDetectResponse.java
backend/src/main/java/com/example/backend/dashboard/service/CaseDetectService.java
backend/src/main/java/com/example/backend/dashboard/service/SseEmitterService.java
backend/src/main/java/com/example/backend/search/controller/SearchController.java
backend/src/main/java/com/example/backend/search/dto/DetailResponse.java
backend/src/main/java/com/example/backend/search/dto/SearchRequest.java
backend/src/main/java/com/example/backend/search/dto/SearchResponse.java
backend/src/main/java/com/example/backend/search/repository/CctvRepository.java
backend/src/main/java/com/example/backend/search/service/SearchService.java

SSE 실시간 알림 API 및 AI 위험 감지 시 사건 저장 API 구현
- #66 
SSE 실시간 알림 및 AI 를 위한 사건 저장 API 구현 완료했습니다.
SSE 통신할 때 CORS 에러가 발생하는데 이는 따로 이슈 파서 해결했으므로 여기서는 무시했습니다! 
리뷰 부탁드려요!

[Backend] feat: SSE 실시간 알림 API 구현

---

backend/src/main/java/com/example/backend/dashboard/controller/AlarmListController.java
backend/src/main/java/com/example/backend/dashboard/dto/AlarmRequest.java
backend/src/main/java/com/example/backend/dashboard/service/AlarmListService.java

알림 리스트 API 수정
- #86 
알림 리스트에서 자세히 보기 클릭 시 사건 상태 "확인"으로 변경하였고,
출동/미출동 클릭 시에 상태 변경하도록 로직 수정했습니다.
리뷰 부탁드려요~

[Backend] fix: 알림 리스트 API 수정

---

.github/workflows/backend-cd.yml

AWS 자동 배포 CD 구축
- #102 
develop에 backend merge 시에 AWS 자동 서버 배포 를 위한 CD 구축 완료했습니다..!
secret key들은 environments에 설정 했습니다..!
리뷰 부탁드려요~

[Backend] feat: AWS 자동 배포 CD 구축

---

backend/src/main/java/com/example/backend/analysis/controller/CaseStatsController.java
backend/src/main/java/com/example/backend/analysis/dto/CaseStatsOverviewResponse.java
backend/src/main/java/com/example/backend/analysis/dto/DailyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/HourlyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/LocationCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/MapCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/MonthlyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/service/CaseStatsService.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseDetectRequest.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseDetectResponse.java
backend/src/main/java/com/example/backend/dashboard/dto/DashboardResponse.java
backend/src/main/java/com/example/backend/search/dto/DetailResponse.java
backend/src/main/java/com/example/backend/search/dto/SearchRequest.java
backend/src/main/java/com/example/backend/search/dto/SearchResponse.java
backend/src/main/java/com/example/backend/search/dto/SearchResult.java
backend/src/main/java/com/example/backend/user/dto/UserResponseDto.java

코드 스타일 통합 및 리팩터링
- #104 
통계 페이지와 기록 조회 페이지 DTO 코드 스타일 통합 및 리팩터링 완료했습니다.
리뷰 부탁드려요~

[Backend] refactor: 코드 스타일 통합 및 리팩터링

---

frontend/.gitignore
frontend/package.json
frontend/src/apis/AlertApi.ts
frontend/src/apis/LoginApi.ts
frontend/src/apis/axiosInstance.ts
frontend/src/components/Login/LoginForm.tsx
frontend/src/components/Monitoring/AlertList/AlertList.tsx
frontend/src/components/Monitoring/AlertModal/AlertModal.tsx
frontend/src/components/Monitoring/AlertModal/CategorySelectModal.tsx
frontend/src/components/Monitoring/AlertModal/IncidentModal.tsx
frontend/src/components/Monitoring/InProgress/CategorySelectCard.tsx
frontend/src/components/Monitoring/InProgress/FeedbackCard.tsx
frontend/src/components/Monitoring/InProgress/InProgress.tsx
frontend/src/components/Monitoring/InProgress/IncidentCard.tsx
frontend/src/components/Monitoring/InProgress/VideoModal/VideoModal.tsx
frontend/src/components/common/VideoComponent/VideoComponent.tsx
frontend/src/constants/EventCategory.ts
frontend/src/hooks/useScrollObserver.ts
frontend/src/mocks/InProgressData.ts
frontend/src/pages/IncidentHistory/page.tsx
frontend/src/pages/Monitoring/page.tsx
frontend/src/stores/itemStore.ts
frontend/src/types/alert.ts
frontend/src/utils/categoryMapper.ts
frontend/vite.config.ts
frontend/yarn.lock

1. 전체 알림, 사건 리스트
2. 알림 리스트 - 자세히 보기 (video)
3. 알림 리스트 - 자세히 보기 (state 업데이트)
1. 전체 출동중인 사건
2. 출동중인 사건 - 영상
3. AI 피드백
4. 출동중인 사건 - 사건 해결
- #61
api 연결하기 쉽게 코드 짜놨더니 금방 했어요 역시 초반에 구조 잘 잡아놓으니 편하네요 ^^

[Frontend] feat: 실시간 모니터링 페이지 API 연동 & 서버 https 실행

---

.github/workflows/backend-cd.yml

…#108
AWS 자동 배포 CD 수정
- #108 
CD 수정 했습니다. 리뷰 부탁드려요.

[Backend] fix: AWS 자동 배포 CD 수정

---

backend/src/main/java/com/example/backend/analysis/controller/CaseStatsController.java
backend/src/main/java/com/example/backend/analysis/service/CaseStatsService.java
backend/src/main/java/com/example/backend/common/GlobalExceptionHandler.java
backend/src/main/java/com/example/backend/config/CorsConfig.java
backend/src/main/java/com/example/backend/config/SecurityConfig.java
backend/src/main/java/com/example/backend/dashboard/controller/CaseDetectController.java
backend/src/main/java/com/example/backend/dashboard/controller/DashboardController.java
backend/src/main/java/com/example/backend/dashboard/service/DashboardService.java

지도용 API 기간 수정
- #110 
지도용 API 기간 월단위로 고정했습니다.

[Backend] fix: 지도용 API 기간 수정

---

frontend/src/apis/ChartApi.ts
frontend/src/components/Chart/BarCard/BarCard.tsx
frontend/src/components/Chart/BarCard/BarFilter/Dropdown/Dropdown.tsx
frontend/src/components/Chart/ClusteringCard/StatsPanel/StatsPanel.tsx
frontend/src/components/Chart/DoughnutCard/DoughnutCard.tsx
frontend/src/components/Chart/LineCard/LineChart.tsx
frontend/src/components/common/CategoryDropDown/CategoryDropDown.tsx
frontend/src/stores/profileStore.ts
frontend/src/utils/dataFormatter.ts

chartPage 에러를 해결했습니다.
- #129 
map 함수 관련해서 발생한 오류들 해결했습니다~ 로그인 안 하고 차트 페이지 들어가보면 console 창에 get 실패 error 메시지가 14개 정도 뜨는데 제가 get을 짜잘하게 해서 어쩔 수 없이 그렇게 되었다는 점 .. 알아주시면 감사하겠습니다람쥐

[Frontend] fix: Chart Page 에러 해결

---

backend/src/main/java/com/example/backend/common/GlobalExceptionHandler.java
backend/src/main/java/com/example/backend/common/domain/CaseEntity.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseDetectResponse.java
backend/src/main/java/com/example/backend/dashboard/repository/DashboardRepository.java
backend/src/main/java/com/example/backend/dashboard/service/CaseDetectService.java
backend/src/main/java/com/example/backend/dashboard/service/DashboardService.java
backend/src/main/java/com/example/backend/search/dto/DetailResponse.java
backend/src/main/java/com/example/backend/search/dto/SearchResponse.java
backend/src/main/java/com/example/backend/search/dto/SearchResult.java

API 오류 수정
- #135 
출동중인 사건에 대한 오류 208로 수정했으며, 프론트 요청에 따라 DB에 출동시각 Column 추가 및 SSE 응답 수정했습니다!
사건 정보 제공 시 정렬도 수정했으니 확인 부탁드립니다! :)

[Backend] fix: API 오류 수정

---

backend/src/main/java/com/example/backend/dashboard/service/DashboardService.java

출동 버튼 클릭시 자동으로 출동 시각 저장되도록 하는 로직에서 DateTimeFormatter 오류 해결
- #139

[Backend] fix: DateTimeFormatter 오류

---

backend/src/main/java/com/example/backend/dashboard/controller/DashboardController.java
backend/src/main/java/com/example/backend/dashboard/service/DashboardService.java
backend/src/main/java/com/example/backend/user/controller/UserController.java

1. 로그아웃 기능 구현했습니다. 세션에서 해당 사용자 정보 삭제하는 방식입니다.
2. DashboardService에서 기존 id 대신 "message"로 리턴 형식 통일했습니다.
- #142

[Backend] feat: logout API

---

.github/workflows/backend-ci.yml
backend/src/main/java/com/example/backend/dashboard/controller/CctvController.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseDetectRequest.java
backend/src/main/java/com/example/backend/dashboard/dto/CctvInfoResponse.java
backend/src/main/java/com/example/backend/dashboard/dto/DashboardResponse.java
backend/src/main/java/com/example/backend/dashboard/repository/CctvInfoRepository.java
backend/src/main/java/com/example/backend/dashboard/service/CctvService.java

메인 화면 CCTV Info 관련 API 개발
- #147 
메인 화면에서 각 Office 별 CCTV 정보 전달 API와 CCTV Id 별 정보 및 실시간 스트리밍 주소 전달 API 개발 완료했습니다.
리뷰 부탁드려요!

[Backend] feat: CCTV Info API 개발

---

backend/src/main/java/com/example/backend/user/controller/UserController.java
backend/src/main/java/com/example/backend/user/service/UserService.java

로그인 아이디 혹은 비밀번호가 잘못됐을시 메세지 반환
- #153 
프론트 요구사항에 따라 에러 대신 200 ok와 메세지를 반환합니다.

[Backend] feat: login 실패시 에러처리

---

backend/src/main/java/com/example/backend/dashboard/dto/CaseDetectRequest.java
backend/src/main/java/com/example/backend/dashboard/service/CaseDetectService.java

카테고리 별 level 자동 처리 로직 추가
- #159 
각 카테고리 별로 level 자동 추가해주는 로직 추가했습니다.
확인 부탁드려요~

[Backend] feat: level 자동 처리 로직 추가

---

backend/src/main/java/com/example/backend/analysis/controller/CaseStatsController.java
backend/src/main/java/com/example/backend/analysis/dto/DailyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/HourlyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/MapCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/dto/MonthlyCaseStatsResponse.java
backend/src/main/java/com/example/backend/analysis/repository/CaseStatsCategoryRepository.java
backend/src/main/java/com/example/backend/analysis/repository/CaseStatsOverviewRepository.java
backend/src/main/java/com/example/backend/analysis/service/CaseStatsService.java
backend/src/main/java/com/example/backend/common/GlobalExceptionHandler.java
backend/src/main/java/com/example/backend/common/domain/CaseEntity.java
backend/src/main/java/com/example/backend/common/domain/CaseStatsCategoryEntity.java
backend/src/main/java/com/example/backend/dashboard/dto/CaseDetectResponse.java
backend/src/main/java/com/example/backend/dashboard/dto/DashboardResponse.java
backend/src/main/java/com/example/backend/dashboard/service/CaseDetectService.java
backend/src/main/java/com/example/backend/dashboard/service/DashboardService.java

- 새로운 카테고리 'smoke' 추가
- 카테고리 추가에 따른 level 자동 매핑 로직 수정
- 통계 페이지 예외 처리 수정
- 통계 페이지 period 기준 수정
- 전체알림리스트 및 SSE API 응답에 cctvId 추가
- #165 
새로운 카테고리 추가 및 프론트에서 말한 수정사항 다 반영 완료 했습니다!
확인 부탁드려요~

[Backend] feat: 카테고리 추가 및 API 수정

---

media/Dockerfile
media/docker-compose.yml
media/nginx.conf

실시간 스트리밍을 위한 미디어 서버 설정
- RTMP, HLS 관련
Dockerfile, docker-compose.yml, nginx.conf 
- #125 
인스턴스에 올라가있는 설정대로 변경했습니다.
추후에 latency를 줄이기위해 교수님과 미팅 후,
큐, 버퍼 등의 수정사항이 있을 예정입니다.

[Media] feat: 미디어 서버 세팅 및 웹캠 실시간 스트리밍

---

AI/ai-pipeline.py

모델 서빙용 AI 서버 로직
- 실시간 스트리밍을 프레임 별로 받아 1차 모델 input
- 1차 모델에서 사람 외 위험 행동 감지 시 백엔드 서버로 POST API 호출
- 1차 모델에서 사람 감지 시 프레임을 모아 약 3초 영상 저장, 2차 모델 input 
- 2차 모델은 해당 input으로 위험 행동 감지 시 백엔드 서버로 POST API 호출
- #181 
실시간 처리를 위해 worker 를 등록하여 1차 모델과 2차 모델을 서로 다른 worker를 배정하였으며, 
공간 확보를 위해 1차 모델에서 프레임을 모아 저장해둔 영상은 input으로 넘어가거나 s3에 저장된 후에는 해당 영상 삭제 처리했습니다.
추가로 작동 중지 시 서버 효율을 위해 worker 할당을 해지하고 중지할 수 있도록 하였습니다.

[AI] feat: 모델 서빙용 AI 서버 로직

---

backend/src/main/java/com/example/backend/dashboard/repository/DashboardRepository.java
backend/src/main/java/com/example/backend/dashboard/service/DashboardService.java

알림리스트 조회 시 24시간 이내 사건들만 조회
- #186 
확인부탁드립니다 :)

[Backend] feat: 알림리스트 조회 기준 추가
